name: genepro
channels:
  - conda-forge
dependencies:
  - ipykernel
  - imagemagick
  - pip=21.2.4 
  - pip:
    - gym
    - pygame
    - pyglet
    - matplotlib
    - numpy
    - scikit-learn
    - sympy